services:

  minio:
    image: quay.io/minio/aistor/minio:RELEASE.2025-12-20T04-58-37Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PUBLIC_BUCKETS: "images"
      MINIO_DEFAULT_BUCKETS: "images"
      MINIO_LICENSE: |
        eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhaWQiOjAsImNhcCI6MCwiaWF0IjoxLjc2NjkzOTU2OTgzODE3MTk1MmU5LCJpc3MiOiJzdWJuZXRAbWluLmlvIiwibGlkIjoiZDE4YjE2MmUtMGRlZC00Y2Y0LWEzZWQtZTBjNTQzOGE4NGVlIiwib3JnIjoiIiwicGxhbiI6IkZSRUUiLCJzdWIiOiJhbGVrc2VqcG9wb3YyNjhAZ21haWwuY29tIiwidHJpYWwiOmZhbHNlfQ.crPZIRBsmI-pdSP4LZRIw3jvVqxm4ln-bkreffbkGM4lTDDPo8eOJJHngRPD3SzIEiIcw-aZSwaXxWQ8RQv6e6MNGFs3yhBaNHU3sh-l-yQyw4XXz1m6ynwItxoy-hJv
      MINIO_CORS_ALLOWED_ORIGINS: "http://localhost:4200,http://frontend:4200"
      MINIO_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
      MINIO_CORS_ALLOWED_HEADERS: "*"
      MINIO_CORS_EXPOSE_HEADERS: "ETag"
      MINIO_CORS_MAX_AGE: "3000"
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - truefood-network

  db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - truefood-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
#    tmpfs: "/datalog"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - truefood-network

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - truefood-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_ENDPOINT: http://minio:9000
      JAVA_OPTS: '-Xmx512m'
    networks:
      - truefood-network

  frontend:
    build: C:\Users\aleks\Desktop\blin-blinskiy\!Курсач\TrueFood
    ports:
      - "4200:4200"
    depends_on:
      - app
    networks:
      - truefood-network
networks:
  truefood-network:
    driver: bridge