services:
  minio:
    image: quay.io/minio/aistor/minio:RELEASE.2025-12-20T04-58-37Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PUBLIC_BUCKETS: "images"
      MINIO_DEFAULT_BUCKETS: "images"
      MINIO_LICENSE: |
        eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhaWQiOjAsImNhcCI6MCwiaWF0IjoxLjc2NjkzOTU2OTgzODE3MTk1MmU5LCJpc3MiOiJzdWJuZXRAbWluLmlvIiwibGlkIjoiZDE4YjE2MmUtMGRlZC00Y2Y0LWEzZWQtZTBjNTQzOGE4NGVlIiwib3JnIjoiIiwicGxhbiI6IkZSRUUiLCJzdWIiOiJhbGVrc2VqcG9wb3YyNjhAZ21haWwuY29tIiwidHJpYWwiOmZhbHNlfQ.crPZIRBsmI-pdSP4LZRIw3jvVqxm4ln-bkreffbkGM4lTDDPo8eOJJHngRPD3SzIEiIcw-aZSwaXxWQ8RQv6e6MNGFs3yhBaNHU3sh-l-yQyw4XXz1m6ynwItxoy-hJv
      MINIO_CORS_ALLOWED_ORIGINS: "http://localhost:4200,http://frontend:4200"
      MINIO_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE"
      MINIO_CORS_ALLOWED_HEADERS: "*"
      MINIO_CORS_EXPOSE_HEADERS: "ETag"
      MINIO_CORS_MAX_AGE: "3000"
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - truefood-network

  db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - truefood-network
  kafka:
    image: apache/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_NUM_PARTITIONS=3
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#      - minio
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      MINIO_ENDPOINT: http://minio:9000
#      MINIO_PUBLIC_ENDPOINT: http://minio:9000
#      JAVA_OPTS: '-Xmx512m'
#    networks:
#      - truefood-network
#
#  frontend:
#    build: C:\Users\aleks\Desktop\blin-blinskiy\!Курсач\TrueFood
#    ports:
#      - "4200:4200"
#    depends_on:
#      - app
#    networks:
#      - truefood-network
networks:
  truefood-network:
    driver: bridge