spring:
  application:
    name: TrueFood
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    enabled: false
    drop-first: false
    change-log: db-migrations/db.changelog-master.yaml
minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: images
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: qBTmv4oXFFR2GwjexDJ4t6dktmnfkhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==