spring:
  application:
    name: TrueFood
  datasource:
    url: jdbc:postgresql://localhost:5432/TrueFood
    username: postgres
    password: 0814
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    #    show-sql: true
#minio:
#  endpoint: http://localhost:9000
#  accessKey: minioadmin
#  secretKey: minioadmin
#  bucket: images
